# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import embedding_stream_pb2 as embedding__stream__pb2


class EmbeddingStreamServiceStub(object):
    """Embedding Stream Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamEmbedding = channel.unary_stream(
                '/embedding.EmbeddingStreamService/StreamEmbedding',
                request_serializer=embedding__stream__pb2.StreamEmbeddingRequest.SerializeToString,
                response_deserializer=embedding__stream__pb2.RowChunk.FromString,
                )


class EmbeddingStreamServiceServicer(object):
    """Embedding Stream Service
    """

    def StreamEmbedding(self, request, context):
        """Python 서버 → Batch 서버로 Streaming 전송
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamEmbedding': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEmbedding,
                    request_deserializer=embedding__stream__pb2.StreamEmbeddingRequest.FromString,
                    response_serializer=embedding__stream__pb2.RowChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'embedding.EmbeddingStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EmbeddingStreamService(object):
    """Embedding Stream Service
    """

    @staticmethod
    def StreamEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/embedding.EmbeddingStreamService/StreamEmbedding',
            embedding__stream__pb2.StreamEmbeddingRequest.SerializeToString,
            embedding__stream__pb2.RowChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
