# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embedding_stream.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x65mbedding_stream.proto\x12\tembedding\"\x81\x01\n\nRecruitRow\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x02 \x01(\t\x12\x11\n\texp_years\x18\x03 \x01(\x05\x12\x15\n\renglish_level\x18\x04 \x01(\t\x12\x17\n\x0fprimary_keyword\x18\x05 \x01(\t\x12\x0e\n\x06vector\x18\x06 \x03(\x02\"/\n\x08RowChunk\x12#\n\x04rows\x18\x01 \x03(\x0b\x32\x15.embedding.RecruitRow\"I\n\x16StreamEmbeddingRequest\x12\x1b\n\x13last_processed_uuid\x18\x01 \x01(\t\x12\x12\n\nchunk_size\x18\x02 \x01(\x05\x32\x65\n\x16\x45mbeddingStreamService\x12K\n\x0fStreamEmbedding\x12!.embedding.StreamEmbeddingRequest\x1a\x13.embedding.RowChunk0\x01\x42\x36\n\x1c\x63om.alpha.backend.grpc.protoB\x14\x45mbeddingStreamProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_stream_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.alpha.backend.grpc.protoB\024EmbeddingStreamProtoP\001'
  _globals['_RECRUITROW']._serialized_start=38
  _globals['_RECRUITROW']._serialized_end=167
  _globals['_ROWCHUNK']._serialized_start=169
  _globals['_ROWCHUNK']._serialized_end=216
  _globals['_STREAMEMBEDDINGREQUEST']._serialized_start=218
  _globals['_STREAMEMBEDDINGREQUEST']._serialized_end=291
  _globals['_EMBEDDINGSTREAMSERVICE']._serialized_start=293
  _globals['_EMBEDDINGSTREAMSERVICE']._serialized_end=394
# @@protoc_insertion_point(module_scope)
