# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embedding_stream.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x65mbedding_stream.proto\x12\x16\x63om.alpha.backend.grpc\"z\n\x16StreamEmbeddingRequest\x12 \n\x13last_processed_uuid\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nchunk_size\x18\x02 \x01(\x05H\x01\x88\x01\x01\x42\x16\n\x14_last_processed_uuidB\r\n\x0b_chunk_size\"<\n\x08RowChunk\x12\x30\n\x04rows\x18\x01 \x03(\x0b\x32\".com.alpha.backend.grpc.RecruitRow\"\x81\x01\n\nRecruitRow\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x02 \x01(\t\x12\x11\n\texp_years\x18\x03 \x01(\x05\x12\x15\n\renglish_level\x18\x04 \x01(\t\x12\x17\n\x0fprimary_keyword\x18\x05 \x01(\t\x12\x0e\n\x06vector\x18\x06 \x03(\x02\"u\n\x11IngestDataRequest\x12:\n\x08metadata\x18\x01 \x01(\x0b\x32&.com.alpha.backend.grpc.IngestMetadataH\x00\x12\x14\n\ndata_chunk\x18\x02 \x01(\x0cH\x00\x42\x0e\n\x0crequest_type\"M\n\x0eIngestMetadata\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x18\n\x10vector_dimension\x18\x03 \x01(\x05\"O\n\x12IngestDataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x17\n\x0freceived_chunks\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t2\xec\x01\n\x16\x45mbeddingStreamService\x12\x65\n\x0fStreamEmbedding\x12..com.alpha.backend.grpc.StreamEmbeddingRequest\x1a .com.alpha.backend.grpc.RowChunk0\x01\x12k\n\x10IngestDataStream\x12).com.alpha.backend.grpc.IngestDataRequest\x1a*.com.alpha.backend.grpc.IngestDataResponse(\x01\x42\x30\n\x16\x63om.alpha.backend.grpcB\x14\x45mbeddingStreamProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_stream_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.alpha.backend.grpcB\024EmbeddingStreamProtoP\001'
  _globals['_STREAMEMBEDDINGREQUEST']._serialized_start=50
  _globals['_STREAMEMBEDDINGREQUEST']._serialized_end=172
  _globals['_ROWCHUNK']._serialized_start=174
  _globals['_ROWCHUNK']._serialized_end=234
  _globals['_RECRUITROW']._serialized_start=237
  _globals['_RECRUITROW']._serialized_end=366
  _globals['_INGESTDATAREQUEST']._serialized_start=368
  _globals['_INGESTDATAREQUEST']._serialized_end=485
  _globals['_INGESTMETADATA']._serialized_start=487
  _globals['_INGESTMETADATA']._serialized_end=564
  _globals['_INGESTDATARESPONSE']._serialized_start=566
  _globals['_INGESTDATARESPONSE']._serialized_end=645
  _globals['_EMBEDDINGSTREAMSERVICE']._serialized_start=648
  _globals['_EMBEDDINGSTREAMSERVICE']._serialized_end=884
# @@protoc_insertion_point(module_scope)
