package com.alpha.api.domain.skilldic.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

/**
 * SkillEmbeddingDic Entity (Domain Model)
 * - Corresponds to "skill_embedding_dic" table in table_specification.md
 * - Stores skill embeddings (1536 dimensions)
 * - UUID is auto-generated by PostgreSQL
 * - Used for skill normalization and query vector creation
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table("skill_embedding_dic")
public class SkillEmbeddingDic {

    public static final int VECTOR_DIMENSION = 1536;

    @Id
    @Column("skill_id")
    private UUID skillId;

    @Column("category_id")
    private UUID categoryId;

    @Column("skill")
    private String skill;

    @Column("skill_vector")
    private List<Float> skillVector;

    @Column("created_at")
    private OffsetDateTime createdAt;

    @Column("updated_at")
    private OffsetDateTime updatedAt;
}
