package com.alpha.api.domain.skilldic.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * SkillCategoryDic Entity (Domain Model)
 * - Corresponds to "skill_category_dic" table in table_specification.md
 * - Stores skill category information (e.g., Backend, Frontend)
 * - UUID is auto-generated by PostgreSQL
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table("skill_category_dic")
public class SkillCategoryDic {

    @Id
    @Column("category_id")
    private UUID categoryId;

    @Column("category")
    private String category;

    @Column("created_at")
    private OffsetDateTime createdAt;

    @Column("updated_at")
    private OffsetDateTime updatedAt;
}
